In [3]:
import numpy as np

print(np.__version__)

2.5.3


In [8]:
#create new array in numpy
a = np.array([1,2,3,4])
print(a)
print(a.dtype) # for check data type
print(a.ndim) # dimension of array
print(a.size) # total size of array
print(a.shape) # share= rows, columns and height of array
print(type(a))

[1 2 3 4]
int64
1
4
(4,)
<class 'numpy.ndarray'>


In [9]:
b = np.array([[1,2,3],[4,5,6]])
print(b.ndim) # dimension of array
print(b.shape) # share= rows, columns and height of array
print(type(b))

2
(2, 3)
<class 'numpy.ndarray'>


In [12]:
#create a array with filled 0 value

c = np.zeros((2,2))
print(c)

[[0. 0.]
 [0. 0.]]


In [14]:
#create a array with filled 1 value

d = np.ones((2,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#create a array with full filled any value

e = np.full((3,2), 9)
print(e)

[[9 9]
 [9 9]
 [9 9]]


In [18]:
# Identity Matrix : diagonal elements are ones and all other elements are zeros

f = np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**arange**

same as in core python use range(1,10,2). in this create a array with same order

In [19]:
arr = np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


**astype()**


In [23]:
ast = np.array([1.23,2.33,3.45])
print(ast.dtype)

float64


In [26]:
newAst = ast.astype(int)
print(newAst.dtype)

int64


In [32]:
add10InA = a+10
sub5InA = a-5
squireInA = a**2
mul5InA = a*5
print(add10InA)
print(sub5InA)
print(squireInA)
print(mul5InA)

[11 12 13 14]
[-4 -3 -2 -1]
[ 1  4  9 16]
[ 5 10 15 20]


In [34]:
r = np.array((4,5,6,7))
print(np.add(a,r))          # add two arrays
print(np.subtract(a,r))     # subtract two arrays
print(np.multiply(a,r))     # multiply two arrays
print(np.divide(a,r))

[ 5  7  9 11]
[-3 -3 -3 -3]
[ 4 10 18 28]
[0.25       0.4        0.5        0.57142857]


**Aggregation function**

In [35]:
print(np.sum(r))

22


In [40]:
print(np.mean(r))
print(np.median(r))
print(np.min(r))
print(np.max(r))
print(np.std(r))
print(np.var(r))

5.5
5.5
4
7
1.118033988749895
1.25


**slicing**

In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:9:2]) # [start:end:step]

[2 4 6 8]


In [10]:
print(arr[-5:-2]) # - indexing start from right to left. it's start from -1 instead of 0. 

[6 7 8]


In [11]:
#reverse => pass -1 in step and start and end will bi blank. in this case array have reverse

print(arr[::-1])

[10  9  8  7  6  5  4  3  2  1]


**Fancy indexing**

In [12]:
#get multi index value from single print

print(arr[[2, 5, 7]])

[3 6 8]


In [18]:
newArr = np.array([10,20,30,40,50,60,70,80,90,100])

print(newArr[newArr > 25])

[ 30  40  50  60  70  80  90 100]


**Reshaping**

In [23]:
print(newArr.reshape(2,5))

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


**IMPORTANT**
ravel and flatten
.ravel = only view, it can be change original array
.flatten = copy, it can make a new array and changes will be in copy array. not any changes in original array.

In [22]:
#revel

multiDiArr = np.array([[1,2,3],[4,5,6]])

print(multiDiArr.ravel())

[1 2 3 4 5 6]


In [24]:
#flatten

print(multiDiArr.flatten())

[1 2 3 4 5 6]


**Insert()**

In [7]:
newArr = np.arange(10,101,10)
print(newArr)

[ 10  20  30  40  50  60  70  80  90 100]


In [9]:
insArr = np.insert(newArr,2, 200, axis=0)
print(insArr)

[ 10  20 200  30  40  50  60  70  80  90 100]


**insert in 2d array**

In [10]:
newArr2D = np.array([[10,20],[30,40]])
print(newArr2D)

insArr2D = np.insert(newArr2D, 1, [50,60], axis=0)
print(insArr2D)

[[10 20]
 [30 40]]
[[10 20]
 [50 60]
 [30 40]]


In [11]:
insArr2DNone = np.insert(newArr2D, 1, [50,60], axis=None)
print(insArr2DNone)

[10 50 60 20 30 40]


**append()**

In [13]:
appArr = np.append(newArr,[55,65])
print(appArr)

[ 10  20  30  40  50  60  70  80  90 100  55  65]


**Concatenate()**

In [15]:
arr1 = np.arange(1,4)
arr2 = np.arange(4,7)

conArr = np.concatenate((arr1,arr2))
print(conArr)

[1 2 3 4 5 6]


**Delete()**

In [17]:
delArr = np.delete(appArr, 2)
print(appArr)
print(delArr)

[ 10  20  30  40  50  60  70  80  90 100  55  65]
[ 10  20  40  50  60  70  80  90 100  55  65]


**Delete from 2D array**

In [19]:
print(newArr2D)

dele2D = np.delete(newArr2D,0,axis=0)
print(dele2D)

[[10 20]
 [30 40]]
[[30 40]]


**Stack()**

**vstack()**

**hstack()**

In [21]:
print(arr1)
print(arr2)

vstack = np.vstack((arr1,arr2))
print(vstack)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [22]:
hstack = np.hstack((arr1,arr2))
print(hstack)

[1 2 3 4 5 6]


**Split()**
**split()**

**hsplit()**

**vsplit()**

In [23]:
splitArr = np.split(appArr,2)
print(splitArr)

[array([10, 20, 30, 40, 50, 60]), array([ 70,  80,  90, 100,  55,  65])]


**Broadcasting()**

solve mathematical problems with array without loop

In [26]:
print(newArr)

#give 10% discount in this array and print after discount value

discount = 10

valueAfterDiscount = newArr - (newArr * discount/100)
print(valueAfterDiscount)

[ 10  20  30  40  50  60  70  80  90 100]
[ 9. 18. 27. 36. 45. 54. 63. 72. 81. 90.]


In [27]:
multiWith1D = newArr * np.array(2)
print(multiWith1D)

[ 20  40  60  80 100 120 140 160 180 200]


In [33]:
multi2D = np.array([[10,20],[30,40]])
multiWith2D = multi2D * multi2D
print(multiWith2D)

[[ 100  400]
 [ 900 1600]]


In [ ]:
Vectorization